#' Summarize the Modeled DGBD Distribution
#'
#' @param df_abundance A data frame that contains abundance data.
#' @param column Either a string with the name of the column or the number of the column that stores the abundances in the data frame.
#' @param BC_plot_object A previous object generated by \code{BC_plot}.
#' @param show_plot Logical. Whether to plot the DGBD distribution. Defaults to true.
#' @param show_stats Logical. Whether to print the parameters of the DGBD distribution and its R2 to the console. Defaults to true.
#'
#' @return A list with the following elements: a matrix that contains the parameters used and their confidence intervals, the R2 and the DGBD plot.
#' @export
#'
#' @examples
#' BC_report(datasets::iris,1)
#'
#' BC_report(datasets::PlantGrowth,"weight",show_plot=FALSE)
#'
#' BC_report(datasets::ToothGrowth,"len",show_stats=FALSE)

BC_report <- function(df_abundance=NULL,column=NULL,BC_plot_object=NULL,show_plot=T,show_stats=T){
  if(!is.null(BC_plot_object)){t_BCplot<- BC_plot_object}
  else if (!is.null(df_abundance)){t_BCplot<-BC_plot(df_abundance,column)}
  else {stop("Neither an abundance data frame or a BC_plot_object were provided")}
  if(show_stats){print("The data fit the DGBD distribution with parameters:")}
  param_matrix <- rbind(t(t_BCplot[[3]])[1,],t_BCplot[[2]],t(t_BCplot[[3]])[2,])
  rownames(param_matrix) <- c("2.5%","50%","97.5%")
  colnames(param_matrix) <- c("A","a","b")
  if(show_stats){print(param_matrix)}
  if(show_stats){print("And the fit has an R2 of:")}
  r2<-t_BCplot[[5]]$adj.r.squared
  if(show_stats){print(r2)}
  if(show_plot){plot(t_BCplot[[7]])}
  summary_output<-list(param_matrix,r2,t_BCplot[[7]])
  invisible(summary_output)
}
