#' Predict Rank Abundance Distribution
#'
#' Uses the parameters calculated by \code{BC_param} to model a DGB distribution from the rank information in the data frame.
#'
#' @param df_abundance A data frame that contains abundance data.
#' @param column_model Either a string with the name of the column or the number of the column that stores the abundances in the data frame.
#' @param BC_param_object Optional. A previous object generated by \code{BC_param}.
#' @param ... passes arguments to \code{BC_param}.
#'
#' @return A list with the following elements: The input data frame with added processed ranking data, model data and confidence interval data, the adjusted parameters, the confidence interval of the parameters, the linear model, a summary of the model and a generated function for use with raw numeric data.
#' @export
#'
#' @examples
#' BC_model(hmp_wgs,2)
#'
#' BC_model(Tara_Data,column_model=1,is_phyloseq=TRUE)
#'
#' BC_model(Tara_Data,column_model=3,is_phyloseq=TRUE,confidence_interval=0.9)
#'

BC_model <- function(df_abundance=NULL,column_model=NULL,BC_param_object=NULL,...){
  if(!is.null(BC_param_object)){temp_data_list <- BC_param_object}
  else if (!is.null(df_abundance)){temp_data_list <- BC_param(df_abundance,column_param=column_model,...)}
  else {stop("Neither an abundance data frame or a BC_param_object were provided")}
  t_frame <- temp_data_list[[1]]
  params <- temp_data_list[[2]]
  #predicted_values <- params["A"]*t_frame[,"pre_numerator"]^params["b"]/(t_frame[,"pre_denominator"]^params["a"])
  BC_predict <- function(rank){params["A"]*(max(t_frame[,"BC_rank"])+1-rank)^params["b"]/(rank^params["a"])}
  predicted_values <- BC_predict(t_frame[,"BC_rank"])
  predicted_values <- ifelse(predicted_values <= 0, .Machine$double.eps, predicted_values)
  predictive_frame <- cbind(t_frame[,1:3],predicted_values,t_frame[,4:length(t_frame[1,])])
  final_data_output <- list(predictive_frame,temp_data_list[[2]],temp_data_list[[3]],temp_data_list[[4]],temp_data_list[[5]],BC_predict)
  return(final_data_output)
}
