#' Summarize the Modeled DGB Distribution
#'
#' @param df_abundance A data frame that contains abundance data.
#' @param column_report Either a string with the name of the column or the number of the column that stores the abundances in the data frame.
#' @param BC_plot_object A previous object generated by \code{BC_plot}.
#' @param show_plot Logical. Whether to plot the DGB distribution. Defaults to true.
#' @param show_stats Logical. Whether to print the parameters of the DGB distribution and its model_extra to the console. Defaults to true.
#' @param ... passes arguments to \code{BC_plot}.
#'
#' @return A list with the following elements: a matrix that contains the parameters used and their confidence intervals, the model_extra vector and the DGBD plot.
#' @export
#'
#' @examples
#' BC_report(EC_Metabolite,2)
#'
#' BC_report(df_abundance=DGBD::MOMv3.3, column_report=7, show_stats=FALSE)
#'
#' BC_report(Tara_Data,2,is_phyloseq=TRUE)
#'

BC_report <- function(df_abundance=NULL,column_report=NULL,BC_plot_object=NULL,show_plot=TRUE,show_stats=TRUE,...){
  if(!is.null(BC_plot_object)){t_BCplot<- BC_plot_object}
  else if (!is.null(df_abundance)){t_BCplot<-BC_plot(df_abundance,column_plot=column_report,...)}
  else {stop("Neither an abundance data frame or a BC_plot_object were provided")}
  if(show_stats){print("The data fit the DGB distribution with parameters:")}
  param_matrix <- rbind(t(t_BCplot[[3]])[1,],t_BCplot[[2]],t(t_BCplot[[3]])[2,])
  t_confint_names <- colnames(t_BCplot[[3]])
  rownames(param_matrix) <- c(t_confint_names[1],"50 %", t_confint_names[2])
  colnames(param_matrix) <- c("A","a","b")
  if(show_stats){print(param_matrix)}
  if(show_stats){print(paste("And the fit has a ",t_BCplot[[8]][1]," of:",sep=""))}
  if(show_stats){print(as.numeric(t_BCplot[[8]][2]))}
  if(show_plot){plot(t_BCplot[[7]])}
  summary_output<-list(param_matrix,t_BCplot[[8]],t_BCplot[[7]])
  invisible(summary_output)
}
